"""
menu_data.py — Hanan Signature Restaurant Menu Data
All menu items organised by category with full metadata.
"""

MENU = {
    "specials": [
        {
            "id": "sp1",
            "name": "Hanan Dum Biryani",
            "price": 28.00,
            "emoji": "🍚",
            "desc": "Slow-cooked basmati rice layered with saffron-marinated mutton, birista (fried onions), kewra water & whole spices. Served with raita, salad & mint chutney.",
            "tags": ["popular", "chef-special"],
            "calories": 980,
            "prep": 45,
            "rating": 5.0,
            "votes": 487,
            "allergens": ["Dairy", "Nuts"],
            "category": "specials"
        },
        {
            "id": "sp2",
            "name": "Royal Nihari — Chef's Pride",
            "price": 24.00,
            "emoji": "🍲",
            "desc": "12-hour slow-braised beef shank in an aromatic gravy of ginger, cardamom & nihari masala. Garnished with ginger julienne, fresh coriander, fried onions & lemon. A Mughal royal heritage dish.",
            "tags": ["popular", "chef-special"],
            "calories": 820,
            "prep": 30,
            "rating": 4.9,
            "votes": 321,
            "allergens": ["Gluten"],
            "category": "specials"
        },
        {
            "id": "sp3",
            "name": "Signature Cast-Iron Karahi",
            "price": 26.00,
            "emoji": "🥘",
            "desc": "Bone-in mutton wok-tossed with hand-crushed tomatoes, green chillies, fresh ginger, black pepper & dried fenugreek. Finished tableside in a sizzling cast-iron karahi.",
            "tags": ["chef-special", "spicy"],
            "calories": 760,
            "prep": 35,
            "rating": 4.9,
            "votes": 298,
            "allergens": ["Dairy"],
            "category": "specials"
        }
    ],
    "starters": [
        {
            "id": "s1",
            "name": "Chicken Tikka",
            "price": 14.99,
            "emoji": "🍗",
            "desc": "Overnight-marinated boneless chicken in yoghurt, Kashmiri red chilli, ginger-garlic paste & lemon juice, chargrilled in a clay tandoor. Served with mint chutney & naan.",
            "tags": ["popular", "gluten-free"],
            "calories": 420,
            "prep": 20,
            "rating": 4.8,
            "votes": 643,
            "allergens": ["Dairy"],
            "category": "starters"
        },
        {
            "id": "s2",
            "name": "Seekh Kebab",
            "price": 13.99,
            "emoji": "🍢",
            "desc": "Minced beef mixed with green chilli, fresh coriander, onion & garam masala, hand-shaped on skewers and grilled over charcoal. Juicy inside, crisp outside.",
            "tags": ["popular"],
            "calories": 380,
            "prep": 18,
            "rating": 4.7,
            "votes": 524,
            "allergens": [],
            "category": "starters"
        },
        {
            "id": "s3",
            "name": "Crispy Samosa (3 pcs)",
            "price": 9.99,
            "emoji": "🥟",
            "desc": "Golden flaky pastry filled with spiced potato, green peas & fresh herbs. Served with tamarind & mint chutneys.",
            "tags": ["vegetarian", "popular"],
            "calories": 340,
            "prep": 12,
            "rating": 4.7,
            "votes": 782,
            "allergens": ["Gluten"],
            "category": "starters"
        },
        {
            "id": "s4",
            "name": "Papri Chaat",
            "price": 11.99,
            "emoji": "🥙",
            "desc": "Crispy flour wafers, boiled chickpeas, potato cubes, whisked yoghurt, sweet tamarind chutney, green chutney & chaat masala. A classic Lahori street-food.",
            "tags": ["vegetarian", "popular"],
            "calories": 310,
            "prep": 8,
            "rating": 4.8,
            "votes": 698,
            "allergens": ["Gluten", "Dairy"],
            "category": "starters"
        },
        {
            "id": "s5",
            "name": "Reshmi Kebab",
            "price": 15.99,
            "emoji": "🍡",
            "desc": "Silky chicken mince blended with cream cheese, cashew paste, green chilli & cardamom — grilled till golden. Extraordinarily tender melt-in-the-mouth texture.",
            "tags": ["gluten-free"],
            "calories": 450,
            "prep": 22,
            "rating": 4.6,
            "votes": 389,
            "allergens": ["Dairy", "Nuts"],
            "category": "starters"
        },
        {
            "id": "s6",
            "name": "Aloo Tikki (4 pcs)",
            "price": 10.99,
            "emoji": "🫓",
            "desc": "Pan-fried spiced potato patties with crushed chickpeas, fresh coriander & pomegranate seeds. Served with yoghurt dip & tamarind sauce.",
            "tags": ["vegetarian"],
            "calories": 360,
            "prep": 15,
            "rating": 4.5,
            "votes": 312,
            "allergens": ["Gluten"],
            "category": "starters"
        },
        {
            "id": "s7",
            "name": "Dahi Bhalle",
            "price": 10.99,
            "emoji": "🥣",
            "desc": "Soft lentil dumplings soaked in chilled sweetened yoghurt, drizzled with tamarind chutney, cumin & red chilli. A beloved Pakistani festive starter.",
            "tags": ["vegetarian"],
            "calories": 290,
            "prep": 10,
            "rating": 4.6,
            "votes": 415,
            "allergens": ["Gluten", "Dairy"],
            "category": "starters"
        },
        {
            "id": "s8",
            "name": "Bun Kebab",
            "price": 12.99,
            "emoji": "🍔",
            "desc": "Lahore's iconic street burger — spicy chicken shami kebab patty, fried egg, pickled onions & coriander chutney in a toasted bun. A Lahori staple.",
            "tags": ["popular"],
            "calories": 480,
            "prep": 14,
            "rating": 4.8,
            "votes": 567,
            "allergens": ["Gluten", "Dairy"],
            "category": "starters"
        }
    ],
    "mains": [
        {
            "id": "m1",
            "name": "Chicken Karahi",
            "price": 21.99,
            "emoji": "🥘",
            "desc": "Bone-in chicken wok-cooked with fresh tomatoes, ginger, green chillies, coriander & Pakistani spices. A Peshawar street-food masterpiece. Served with naan.",
            "tags": ["popular", "spicy"],
            "calories": 620,
            "prep": 28,
            "rating": 4.9,
            "votes": 987,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m2",
            "name": "Mutton Dum Biryani",
            "price": 24.99,
            "emoji": "🍚",
            "desc": "Fragrant long-grain basmati layered with slow-braised mutton, saffron, rose water, fried onions & whole spices. Slow-cooked on dum (sealed steam).",
            "tags": ["popular"],
            "calories": 890,
            "prep": 40,
            "rating": 4.8,
            "votes": 812,
            "allergens": ["Dairy", "Nuts"],
            "category": "mains"
        },
        {
            "id": "m3",
            "name": "Dal Makhani",
            "price": 16.99,
            "emoji": "🫕",
            "desc": "Black urad lentils & kidney beans slow-cooked overnight, finished with butter, cream & a smoky tandoor finish. The queen of Pakistani dals.",
            "tags": ["vegetarian", "popular"],
            "calories": 520,
            "prep": 20,
            "rating": 4.8,
            "votes": 724,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m4",
            "name": "Palak Gosht",
            "price": 22.99,
            "emoji": "🍃",
            "desc": "Tender boneless mutton braised in vibrant spinach purée, garlic, ginger & warming spices. Rich, earthy & deeply satisfying.",
            "tags": ["gluten-free"],
            "calories": 640,
            "prep": 30,
            "rating": 4.7,
            "votes": 567,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m5",
            "name": "Chicken Handi",
            "price": 19.99,
            "emoji": "🍛",
            "desc": "Boneless chicken slow-cooked in a clay handi pot with rich tomato-cream gravy, dried fenugreek, cashew paste & aromatic spices. Thick and indulgent.",
            "tags": ["popular"],
            "calories": 680,
            "prep": 25,
            "rating": 4.8,
            "votes": 634,
            "allergens": ["Dairy", "Nuts"],
            "category": "mains"
        },
        {
            "id": "m6",
            "name": "Haleem",
            "price": 18.99,
            "emoji": "🥣",
            "desc": "A beloved Pakistani slow-cook — shredded beef & broken wheat simmered for hours with whole spices until thick & silky. Topped with ginger, lime, fried onions & coriander.",
            "tags": ["popular"],
            "calories": 580,
            "prep": 15,
            "rating": 4.9,
            "votes": 743,
            "allergens": ["Gluten"],
            "category": "mains"
        },
        {
            "id": "m7",
            "name": "Aloo Gosht",
            "price": 20.99,
            "emoji": "🍖",
            "desc": "Classic Pakistani home-style mutton & potato curry — tender chunks slow-braised in a rich onion-tomato gravy. Pure comfort food, served with hot naan.",
            "tags": ["gluten-free"],
            "calories": 710,
            "prep": 35,
            "rating": 4.6,
            "votes": 489,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m8",
            "name": "Daal Tadka",
            "price": 14.99,
            "emoji": "🫙",
            "desc": "Yellow lentils simmered with turmeric & ginger, finished with a sizzling tadka of whole cumin, dried red chilli, garlic & desi ghee.",
            "tags": ["vegetarian", "vegan", "gluten-free"],
            "calories": 410,
            "prep": 20,
            "rating": 4.6,
            "votes": 531,
            "allergens": [],
            "category": "mains"
        },
        {
            "id": "m9",
            "name": "Chicken Biryani",
            "price": 20.99,
            "emoji": "🍚",
            "desc": "Aromatic basmati rice layered with spiced bone-in chicken, saffron, fried onions & fresh mint. A classic that never disappoints.",
            "tags": ["popular"],
            "calories": 820,
            "prep": 38,
            "rating": 4.8,
            "votes": 754,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m10",
            "name": "Paya (Trotters)",
            "price": 22.99,
            "emoji": "🦴",
            "desc": "Slow-cooked lamb trotters in a rich, collagen-rich broth with ginger, garlic & whole spices. A traditional Pakistani breakfast & dinner favourite.",
            "tags": ["gluten-free"],
            "calories": 540,
            "prep": 20,
            "rating": 4.7,
            "votes": 398,
            "allergens": [],
            "category": "mains"
        },
        {
            "id": "m11",
            "name": "Lahori Chargha",
            "price": 23.99,
            "emoji": "🍗",
            "desc": "Whole chicken marinated in spiced yoghurt & steamed, then deep-fried until golden and crispy. A signature Lahori dish served with raita & salad.",
            "tags": ["popular", "spicy"],
            "calories": 890,
            "prep": 40,
            "rating": 4.9,
            "votes": 612,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m12",
            "name": "Saag Paneer",
            "price": 17.99,
            "emoji": "🟩",
            "desc": "Fresh cottage cheese cubes in a rich, slow-cooked mustard greens & spinach purée with garlic, ginger & desi ghee. Vibrant, hearty & vegetarian.",
            "tags": ["vegetarian", "gluten-free"],
            "calories": 480,
            "prep": 22,
            "rating": 4.6,
            "votes": 421,
            "allergens": ["Dairy"],
            "category": "mains"
        },
        {
            "id": "m13",
            "name": "Keema Naan",
            "price": 13.99,
            "emoji": "🫓",
            "desc": "Freshly baked tandoor naan stuffed with spiced minced beef, green chillies & onions. Served with mint chutney — a meal in itself.",
            "tags": ["popular"],
            "calories": 520,
            "prep": 18,
            "rating": 4.7,
            "votes": 689,
            "allergens": ["Gluten", "Dairy"],
            "category": "mains"
        },
        {
            "id": "m14",
            "name": "Mutton Roghan Josh",
            "price": 24.99,
            "emoji": "🥘",
            "desc": "Kashmiri-style mutton braised in a vibrant red gravy of Kashmiri chilli, fennel & whole spices. Aromatic, bold & strikingly beautiful.",
            "tags": ["gluten-free"],
            "calories": 700,
            "prep": 40,
            "rating": 4.8,
            "votes": 456,
            "allergens": ["Dairy"],
            "category": "mains"
        }
    ],
    "desserts": [
        {
            "id": "d1",
            "name": "Gulab Jamun (3 pcs)",
            "price": 8.99,
            "emoji": "🍮",
            "desc": "Soft milk dumplings fried golden, soaked in rose-infused saffron sugar syrup with green cardamom. The ultimate Pakistani comfort dessert.",
            "tags": ["vegetarian", "popular"],
            "calories": 520,
            "prep": 8,
            "rating": 4.9,
            "votes": 1023,
            "allergens": ["Gluten", "Dairy"],
            "category": "desserts"
        },
        {
            "id": "d2",
            "name": "Kheer",
            "price": 9.99,
            "emoji": "🥛",
            "desc": "Slow-cooked creamy rice pudding with full-fat milk, green cardamom, crushed pistachios & rose water. Chilled overnight. Pure nostalgia.",
            "tags": ["vegetarian", "gluten-free"],
            "calories": 440,
            "prep": 5,
            "rating": 4.8,
            "votes": 812,
            "allergens": ["Dairy", "Nuts"],
            "category": "desserts"
        },
        {
            "id": "d3",
            "name": "Shahi Tukray",
            "price": 10.99,
            "emoji": "🍞",
            "desc": "Royal bread pudding — fried bread soaked in saffron-cardamom rabri (condensed milk), garnished with silver leaf, crushed almonds & rose petals.",
            "tags": ["vegetarian", "popular"],
            "calories": 610,
            "prep": 10,
            "rating": 4.7,
            "votes": 678,
            "allergens": ["Gluten", "Dairy", "Nuts"],
            "category": "desserts"
        },
        {
            "id": "d4",
            "name": "Gajar Halwa",
            "price": 9.99,
            "emoji": "🥕",
            "desc": "Slow-cooked grated carrot halwa in desi ghee, whole milk, sugar & green cardamom. Topped with crushed pistachios & served warm.",
            "tags": ["vegetarian", "gluten-free"],
            "calories": 490,
            "prep": 8,
            "rating": 4.7,
            "votes": 589,
            "allergens": ["Dairy", "Nuts"],
            "category": "desserts"
        },
        {
            "id": "d5",
            "name": "Rasmalai",
            "price": 11.99,
            "emoji": "🍡",
            "desc": "Velvety cottage cheese dumplings in chilled saffron-cream sauce with green cardamom & crushed pistachios. Light, delicate & utterly divine.",
            "tags": ["vegetarian", "gluten-free", "popular"],
            "calories": 390,
            "prep": 5,
            "rating": 4.9,
            "votes": 756,
            "allergens": ["Dairy", "Nuts"],
            "category": "desserts"
        },
        {
            "id": "d6",
            "name": "Kulfi (2 pcs)",
            "price": 9.99,
            "emoji": "🍦",
            "desc": "Traditional frozen Pakistani ice cream — dense, creamy & intensely flavoured with cardamom, pistachio & rose water. Served on a stick.",
            "tags": ["vegetarian", "gluten-free"],
            "calories": 360,
            "prep": 4,
            "rating": 4.8,
            "votes": 634,
            "allergens": ["Dairy", "Nuts"],
            "category": "desserts"
        },
        {
            "id": "d7",
            "name": "Zarda (Sweet Rice)",
            "price": 10.99,
            "emoji": "🍯",
            "desc": "Festive saffron-tinted sweet rice, cooked with sugar, cardamom, raisins, almonds & silver leaf. Traditionally served at celebrations.",
            "tags": ["vegetarian"],
            "calories": 510,
            "prep": 8,
            "rating": 4.6,
            "votes": 398,
            "allergens": ["Dairy", "Nuts", "Gluten"],
            "category": "desserts"
        }
    ],
    "drinks": [
        {
            "id": "dr1",
            "name": "Mango Lassi",
            "price": 6.99,
            "emoji": "🥭",
            "desc": "Thick chilled blend of fresh Alphonso mango pulp, full-fat yoghurt, sugar & a pinch of cardamom. Creamy, sweet & incredibly refreshing.",
            "tags": ["vegetarian", "popular"],
            "calories": 220,
            "prep": 5,
            "rating": 4.9,
            "votes": 1145,
            "allergens": ["Dairy"],
            "category": "drinks"
        },
        {
            "id": "dr2",
            "name": "Kashmiri Chai (Pink Tea)",
            "price": 5.99,
            "emoji": "🍵",
            "desc": "Iconic blush-pink Kashmiri tea brewed with gunpowder green tea, milk, baking soda & cardamom. Topped with almond flakes & pistachios.",
            "tags": ["vegetarian"],
            "calories": 180,
            "prep": 8,
            "rating": 4.8,
            "votes": 834,
            "allergens": ["Dairy", "Nuts"],
            "category": "drinks"
        },
        {
            "id": "dr3",
            "name": "Sweet Lassi",
            "price": 5.99,
            "emoji": "🥛",
            "desc": "Chilled yoghurt whisked with sugar, ice & rose water. Cool, light and wonderfully refreshing.",
            "tags": ["vegetarian", "popular"],
            "calories": 190,
            "prep": 4,
            "rating": 4.7,
            "votes": 723,
            "allergens": ["Dairy"],
            "category": "drinks"
        },
        {
            "id": "dr4",
            "name": "Rooh Afza Sharbat",
            "price": 4.99,
            "emoji": "🌹",
            "desc": "Classic Pakistani rose-based concentrate with chilled milk. Floral, sweet & utterly nostalgic. A beloved Iftar favourite.",
            "tags": ["vegetarian", "popular"],
            "calories": 140,
            "prep": 3,
            "rating": 4.6,
            "votes": 612,
            "allergens": ["Dairy"],
            "category": "drinks"
        },
        {
            "id": "dr5",
            "name": "Doodh Patti Chai",
            "price": 4.99,
            "emoji": "☕",
            "desc": "Traditional Pakistani milk tea brewed strong with Assam leaves, whole cardamom & fresh ginger. No water added — pure doodh patti bliss.",
            "tags": ["popular"],
            "calories": 120,
            "prep": 6,
            "rating": 4.8,
            "votes": 945,
            "allergens": ["Dairy"],
            "category": "drinks"
        },
        {
            "id": "dr6",
            "name": "Fresh Lime Soda",
            "price": 4.99,
            "emoji": "🍋",
            "desc": "Freshly squeezed lime, sparkling soda, mint, kala namak & cumin. Choose sweet, salted or mixed.",
            "tags": ["vegan"],
            "calories": 60,
            "prep": 3,
            "rating": 4.6,
            "votes": 498,
            "allergens": [],
            "category": "drinks"
        },
        {
            "id": "dr7",
            "name": "Jaljeera",
            "price": 4.99,
            "emoji": "🌿",
            "desc": "Tangy chilled drink made with cumin, mint, tamarind, black salt & lemon. A cooling, digestive drink perfect after a spicy meal.",
            "tags": ["vegan", "popular"],
            "calories": 55,
            "prep": 3,
            "rating": 4.7,
            "votes": 576,
            "allergens": [],
            "category": "drinks"
        },
        {
            "id": "dr8",
            "name": "Sugarcane Juice",
            "price": 5.99,
            "emoji": "🎋",
            "desc": "Freshly pressed sugarcane with ginger, lemon & a pinch of black salt. Sweet, earthy & incredibly energising.",
            "tags": ["vegan"],
            "calories": 110,
            "prep": 5,
            "rating": 4.8,
            "votes": 489,
            "allergens": [],
            "category": "drinks"
        }
    ]
}

# Flat lookup map: id → item
ALL_ITEMS = {item["id"]: item for items in MENU.values() for item in items}

CATEGORY_LABELS = {
    "all":      "All Categories",
    "specials": "Chef's Signatures",
    "starters": "Starters & Snacks",
    "mains":    "Main Course",
    "desserts": "Desserts & Mithai",
    "drinks":   "Drinks & Beverages"
}

TAX_RATE     = 0.08875   # 8.875%
SERVICE_RATE = 0.12      # 12%